### ISSUE TITLE
How to display Google Home Timers?

### ISSUE THREAD

**Issue by mrand** [pmongloid/flipdown-timer-card#10]
There is a now custom component to access Google timers: https://github.com/leikoilja/ha-google-home#timers

Displaying that raw timer as an entity in a lovelace entities card displays a count-down time:

![image](https://user-images.githubusercontent.com/435987/144736224-03217244-420c-4855-a5df-23bc17a82380.png)

I have an always on display that I'd love to use your flipdown card to show it instead.

Below shows a set of templates I stole from issue 19 of https://github.com/rianadon/timer-bar-card/issues/ to extract the timer from the Google timers array, but I'm guessing that the flipdown card doesn't trigger on end_time, and instead wants "remaining"?   Ignoring that the remaining below isn't properly formatted (I think your code desires HH:MM:SS, correct?), it isn't great because the remaining seconds regularly freezes and then catches up by jumping many seconds.  I don't suppose there is a way to present the flipdown card with just the end_time so the card can count smoothly?

```
  - sensor:
    - name: "Kitchen Timer"
      icon: mdi:timer
      state: >
        {% set entity = 'sensor.kitchen_speaker_timers' %}
        {% if state_attr(entity,'timers')|lower not in ['','[]','unknown','unavailable','none'] %}
          {% set status = state_attr(entity,'timers')[0].status %}
          {% if status == 'set' %} active
            {% elif status == 'paused' %} paused
            {% elif status == 'waiting' %} waiting
            {% else %} idle
          {% endif %}
        {% endif %}
      attributes:
        remaining: >
          {% set entity = 'sensor.kitchen_speaker_timers' %}
          {% if state_attr(entity,'timers')|lower not in ['','[]','unknown','unavailable','none'] %}
            {{ as_timestamp( state_attr(entity,'timers')[0].local_time_iso) - as_timestamp(now())}}
          {% endif %}
        duration: >
          {% set entity = 'sensor.kitchen_speaker_timers' %}
          {% if state_attr(entity,'timers')|lower not in ['','[]','unknown','unavailable','none'] %}
            {{ state_attr(entity,'timers')[0].duration }}
          {% endif %}
        end_time: >
          {% set entity = 'sensor.kitchen_speaker_timers' %}
          {% if state_attr(entity,'timers')|lower not in ['','[]','unknown','unavailable','none'] %}
            {{ state_attr(entity,'timers')[0].local_time_iso }}
          {% endif %}
        integration: google_home
```
Here are the actual attributes, followed by the sensors I created:

![image](https://user-images.githubusercontent.com/435987/144735194-cf29c188-d893-473a-810f-d554d451aa9a.png)

Thanks!

**Comment by pmongloid** [comment]
The end time is calculated by adding the 'remaining' to 'last_changed' for an entity(identical to built-in lovelace card).
So the 'remaining' attribute must keep initial duration and remain fixed during active state.
I will consider supporting non-timer entities like timer-bar-card.

**Comment by pmongloid** [comment]
it looks like you can use the template for the 'duration' as 'remaining'.

**Comment by mrand** [comment]
Using the template for the 'duration' as 'remaining' worked for the most part.  My wife loves the Flipcard display!

Some observations, most of which I suspect are due to the Google Home custom component and nothing you can do anything about:

1. There is a considerable number of seconds delay (varies up to ~30?) between telling Goggle Home to start the timer, and the timer goes active. Developers tools entity list confirms that the timer isn't active, so not the fault of flipdown card - just documenting it here in case others wonder.  The end result is that HA (and Flipdown) run some number of seconds behind the actual timer.
2. Not consistently, but on occasion, the Flipdown card displays the new timer but freezes and doesn't count.  After a 10-20 second delay, sometimes it catches up (minus the Google Home delay described above).  Other times it requires a browser refresh.  Not a huge deal.
3. **Adding** time to the timer works, although Flipdown card doesn't add the time until the seconds roll over (not a huge deal)
4. Restarting the timer for a different time, results in strange behavior from Flipdown.  Seems like sometimes Flipdown ignores the new time.  Or Flipdown will adjust some digits, but not all.  
5. As expected, since this isn't an HA timer, cancel and stop buttons don't work.  Stop (which I assume means Pause) doesn't appear to be supported by Google Home, but Cancel (aka Delete) is.  Adding the ability to link a service to the Cancel/Delete button would almost get us there, but it would also need to pass the [token/timer_id](https://github.com/leikoilja/ha-google-home#delete-alarm).
<strike>6. I was able to hide the stop and cancel buttons by making the button width 0 px since they don't work currently</strike>  Missed the config option

I'll let you decide if you want to keep this issue open or close it.   Thanks again!!

**Comment by pmongloid** [comment]
First of all, hiding button is supported.
Check button location on README

**Comment by pmongloid** [comment]
it seems the google timer integration updates its state by polling(every 30 seconds or more) and it causes timing error.
i will support 'end_time' attribute on next update, then everything will be solved.
i will close this issue after the update.

**Comment by mrand** [comment]
So we've been using this more and have noticed that when the flipdown card is frozen (when a new timer is commanded), refreshing the web browser (on our always-up computer monitor) is required to resolve it.

**Comment by max5962** [comment]
i would like to add you awesome flipdown timer with my google home timer.
any news about that ticket ?
