### ISSUE TITLE
Display on Home Assistant companion on iOS Devices possible?

### ISSUE THREAD

**Issue by Chiabotti** [pmongloid/flipdown-timer-card#11]
Hi,
I installed the flip-down timer card and it works great - exactly what I was looking for. 
Issue is that the card is not dislayed on my wall mounted iPad devices. Any hints how this can be achieved?

Thanks for the feedback,
Aleardo

**Comment by pmongloid** [comment]
It works well on my wife's iphone 12.
Tested on safari and HA companion.

**Comment by Chiabotti** [comment]
mmhhh strange. Will check further then and close the issue.

Thanks for the feedback and sorry for the false alarm!
