### ISSUE TITLE
Can't make hours work

### ISSUE THREAD

**Issue by elchanly** [pmongloid/flipdown-timer-card#12]
Hi!
First: good job, it's a very nice card, so useful and beautiful.
I had it when it didnt hide seconds and i updated it today with the new feature "show_hours: auto".
It does it, hides automatically to HH:MM (seems to...) but when I click on supposed hours, it's minutes. Timer tells that.
I checked it several times, in several ways, but i cant make it do it well :(

By the way, a little typo in your readme.md:  you have to put "show_hours: auto" instead of "show_hour: auto" to make this work.

Thanks a lot for this card, its so beautiful!

**Comment by pmongloid** [comment]
Can you explain the problem again after setting `show_header: true` ?
Thanks.

**Comment by elchanly** [comment]
This code:
          - type: custom:flipdown-timer-card
            entity: timer.olla
            show_hours: auto
            show_title: true
            show_header: true
            theme: dark
            duration: '00:00:00'
            styles:
              rotor:
                width: 50px
                height: 70px
              button:
                width: 60px
                location: right
Shows minutes and seconds, not hours and mins :(

**Comment by pmongloid** [comment]
There was a confusion on show_hour setting because of my english skill.
finally, `show_hour : auto` is right on this card.
Maybe gramatically wrong? I don't know.

**Comment by elchanly** [comment]
Oh! show_hour works! Sorry, but it was only my fault: i wrote hourS without thinking and then shit happened.

So sorry, now it works beautifully. Thanks for your excellent work!
