### ISSUE TITLE
Fix resize card that fit to mobile screen

### ISSUE THREAD

**Issue by caohuongls** [pmongloid/flipdown-timer-card#17]
When display card on mobile,  it's become vertical card instead of horizontal card due to lack of space.  
So why don't you rezise all content of card to fit width of mobile screen
Thanks

![Screenshot_20220422-124254_Home Assistant.jpg](https://user-images.githubusercontent.com/17307638/164610969-43580a76-228c-4500-99fa-97e215a98d7a.jpg)

**Comment by BebeMischa** [comment]
You can resize yourself to any size, you like. Read manual.

**Comment by caohuongls** [comment]
![image](https://user-images.githubusercontent.com/17307638/164746278-d4927ffe-8a48-412f-bc61-700d4d77c68e.png)

If I have 2 colums in row card. It'll make card narrow. For example, if i set 20px rotor width, the number not small equal with the square of value inside.
And if I resize with this, It's not compatible between diffrent size of each device width.

**Comment by pmongloid** [comment]
I have never considered horizontal stacks.
Let me see its fixable easily since I'm not working on this card actively nowadays.

**Comment by caohuongls** [comment]
Thanks for reply me,
I suggest upgrade UI. 
Instead of change value for each number in hour, minute or second. You can change value for both of them ( for example, it like as set value on clock on some android phone)

And I have one more question. Can I add only hours, minutes without second in UI ?.

**Comment by pmongloid** [comment]
i am also not satisfied with the way of time picker..
but it's a bit difficult to do something now.

hiding seconds is not supported.
why don't you use auto_hours?
