### ISSUE TITLE
Height of buttons "start", "stop" ...

### ISSUE THREAD

**Issue by Protoncek** [pmongloid/flipdown-timer-card#18]
Hello!
I love your timer card, however i think that mentioned buttons, if positioned "below" are pretty small (in height), so it's hard to press it, especially on phone. Do you have the possibility to add "height: ..px" to button configuration?

Thanks!
Best regards, Pavel

**Comment by pmongloid** [comment]
Added

**Comment by Protoncek** [comment]
GREAT! 
many, many thanks!
