### ISSUE TITLE
Timer Issue

### ISSUE THREAD

**Issue by avviano** [pmongloid/flipdown-timer-card#19]
I have my timer set to 40 hours in my configuration yaml. When I set up my dashboard flipcard, the timer keeps resetting to 16:00:00. No idea where this number is coming from. When I click on the card it says "Attribute is 16 hours". It seems that there is a timer limit set by your script to 16 hours?

**Comment by avviano** [comment]
![image](https://user-images.githubusercontent.com/64299639/172054739-94dad34f-cfb8-4642-944b-bf2e94d03034.png)

Attribute is 40 hours in confiuration.yaml, which also shows as "Attribute" under "Helpers". As soon as I use my timer in your "flipdown-timer-card", it resets the timer attribute to 16 hours, even in my "helper" list. Why is that?

**Comment by avviano** [comment]
I think I know what is happening. When I enter 25 hours, it will reset to 1 hour. If I enter 40 hours, it will reset and start the timer at 16 hours. The script deducts 24 hours of any value entered which is larger than 24 hours. So any number larger than 24 - 24 = reset timer. Why would you limit the timer in the script to 24 hours? Home Assistant doesn't limit the timer, so it would only make sense that the script follows suite. Cool timer though, except the 24 hour limitation.

**Comment by pmongloid** [comment]
The original code I used has days but I removed it.
40hours became 1day and 16hours and we have no room for days.
It can be fixed easily.. but I'm not sure how to handle more than 100hours then.

**Comment by pmongloid** [comment]
New update will work for under 99 hours.

**Comment by avviano** [comment]
Thank you, great to hear about the update! Cheers
