### ISSUE TITLE
[feature suggestion]

### ISSUE THREAD

**Issue by Stooovie** [pmongloid/flipdown-timer-card#2]
UX improvement suggestion: tap the upper portion to increase the number, tap the lower half to decrease it. It would be very intuitive. Thanks!

**Comment by pmongloid** [comment]
This will be implemented on next update.
But need to think about the animation effect for duration set since making flipping up effect is a huge job.
Thanks for suggestion.

**Comment by Jac-Kok** [comment]
Nice Work!

Maybe also an idea, to play a sound when the timer is up?
And the ability to enter text so you know what the timer is for?
This would allow you to use the timer for multiple purposes.
(A static title is now possible)

**Comment by BebeMischa** [comment]
You can set that sound up easily in an automation yourself like this, @Jac-Kok 

```
alias: Timer stop
description: ''
trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.aardappels
condition: []
action:
  - service: media_player.play_media
    target:
      entity_id: media_player.vlc_telnet
    data:
      media_content_id: http://192.168.178.79:8123/local/ns-ding-dong.mp3
      media_content_type: music
mode: single

**Comment by pmongloid** [comment]
producing a sound will only work while you are watching the timer since this card is just frontend integration.
maybe this is not what you want.
