### ISSUE TITLE
Is there a way to hide the card when timer is inactive?

### ISSUE THREAD

**Issue by SergeantPup** [pmongloid/flipdown-timer-card#20]
Hello, this card suddenly just started working with my alexa integration and its a perfect visual representation of what i wanted.  I have an absurd amount of timer devices and while I'd love to get them all on this feature, to do so without a way to hide each card when inactive will make a messy dashboard.  I reviewed the documentation twice and I didn't see any issues/threads for this.  Is there a way to hide the card in lovelace when the timer is inactive?

**Comment by pmongloid** [comment]
i think you can use this.
anyway i did nothing with alexa stuff, i dunno why it's working suddenly.

https://www.home-assistant.io/dashboards/conditional/

**Comment by SergeantPup** [comment]
That worked perfectly, thank you!
