### ISSUE TITLE
Card editor messed up

### ISSUE THREAD

**Issue by SteveRMann** [pmongloid/flipdown-timer-card#22]
In Home Assistant 2022.7.6, the card editor is a mess:
![flip card configuration](https://user-images.githubusercontent.com/8091425/180347293-90cdc02f-01ed-4ff5-a403-7e5b26a8e52d.jpg)

I can edit it in YAML, but not in the GUI.
![flip card card yaml](https://user-images.githubusercontent.com/8091425/180347522-58c7b891-9202-4172-ae46-370fc4a2d4cd.jpg)

Home Assistant 2022.7.6
Supervisor 2022.07.0
Operating System 8.2
Frontend 20220707.1 - latest
Browser: Chrome Version 103.0.5060.134 (Official Build) (64-bit)

**Comment by HybridRCG** [comment]
Same here. 
Would love the ability to use days as well, not just hours/minutes/seconds.

**Comment by pmongloid** [comment]
GUI configuration is not supported..

**Comment by CptKalibak** [comment]
> Same here. Would love the ability to use days as well, not just hours/minutes/seconds.

I second that. Days & Hours is what i am looking for.
