### ISSUE TITLE
Boilerplate card?

### ISSUE THREAD

**Issue by BebeMischa** [pmongloid/flipdown-timer-card#26]
Just got a shock, when prompted for the update. I was like: What? Update Boilerplate card? I do not have that!

So, after digging into it, just a question: Why it had to be renamed?

Flipdown Timer is easy an recognizable for everyone, Boilerplate I even never heard of something like that...

**Comment by pmongloid** [comment]
I messed up something during the update.
I am trying to put it back again...but dunno where to change yet.

**Comment by BebeMischa** [comment]
Super fast fix! Thank you very much ;-)
