### ISSUE TITLE
Can't find this in HACS

### ISSUE THREAD

**Issue by JeffCrum1** [pmongloid/flipdown-timer-card#32]
Has this been removed from HACS?  I don't see it in a search.

**Comment by BebeMischa** [comment]
add repository manually should help you solve it fast :-)

**Comment by JeffCrum1** [comment]
Thanks for that.  When I try, HACS tells me it is already in the store.

Googling tells me I have to uninstall and reinstall HACS to fix this.  Grrrr

Thanks for the suggestion.
