### ISSUE TITLE
Wrong time shown 

### ISSUE THREAD

**Issue by harrerzoltan** [pmongloid/flipdown-timer-card#35]
**Checklist:**

- [x ] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Release with the issue:**

**Browser and Operating System:**
Win 11, Chrome

**Description of problem:**

It shows different time when it runs. Like it has ~6 seconds late in running state than if it paused

![meh](https://github.com/pmongloid/flipdown-timer-card/assets/90988592/a2ac7920-7297-4b1a-80f9-df116b026cf7)

**Comment by pmongloid** [comment]
It's because of time mismatch between ha server and client. The default timer card will show same result.

**Comment by harrerzoltan** [comment]
OK, got it.
