### ISSUE TITLE
Rest Button

### ISSUE THREAD

**Issue by naproxes** [pmongloid/flipdown-timer-card#6]
I expected the reset Button to Set the Flipdowns to the Home Assistent Timer helper time.
This only works as long i don't Hit Start. After that the timer only resets to the time set via the Flipdowns.

Is this behavior intended? Is there a way to change that?

**Comment by pmongloid** [comment]
it's intended. 
You can just remove duration setting because it's optional.
Refer to main page about duration setting.

**Comment by naproxes** [comment]
I knew it worked some time in the process of my setup but i thought it was a Bug.
Now that i Set the duration, the reset Button Sets the time as desired!
Thanks!

PS: there is a typo in the readme for "show_hour[s]"

**Comment by pmongloid** [comment]
Thanks. Glad that it's working well.
