### ISSUE TITLE
Enhancement suggestion: 2 Flips, auto hours to seconds

### ISSUE THREAD

**Issue by ImagineerNL** [pmongloid/flipdown-timer-card#7]
As long as my counter is over one hour i dont mind the seconds. 
would be nice if the flips could remain 2 and switch to seconds
01:05 hours:minutes
55:30 minutes:seconds

For the rest; awesome tool

**Comment by BebeMischa** [comment]
Yeah, I need that too. Keeping the timer small on lovelace this wil help so much!

just add option

```
show second: false

```

would be fine with me :-)

**Comment by ImagineerNL** [comment]
Great suggestion and sounds like an enhancement as well, but that doesnt do it for me. (as it will drop down to 1 'flip' when it is below the hour.)
Implementing both options would be perfect then :)

**Comment by pmongloid** [comment]
added auto-hour mode
