### ISSUE TITLE
Unexpected token 'export'

### ISSUE THREAD

**Issue by mrand** [pmongloid/flipdown-timer-card#9]
Just trying flipdown for the first time, and doing so with 2021.11.5.  I've been using HA for a number of years now, including custom components and cards, installed both manually and via HACS.  So... not sure if this is a problem with my install, or a problem with the card itself.  Not a JS coder, but happy to help with extra debug or test loads.

2021-11-28 20:39:25 ERROR (MainThread) [frontend.js.latest.202111090] http://192.168.1.23:8123/hacsfiles/flipdown-timer-card/flipdown-timer-card.js:498:218 Uncaught SyntaxError: Unexpected token 'export'

Perhaps unrelated, but going to 

Configuration > Lovelace Dashboards > Resources, I note that it says that is labels this card as "deprecated" 
Not sure if it's because of the above error, or some other reason.

Thanks!

**Comment by pmongloid** [comment]
which browser did you use? Isn't it old one?

**Comment by mrand** [comment]
Chrome is up to date: 
Version 96.0.4664.45 (Official Build) (64-bit)

**Comment by pmongloid** [comment]
hmm.. is type 'module' in yaml?

resources:
  - url: flipdown-timer-card.js
    type: module

**Comment by mrand** [comment]
Great minds think alike :-)   After I commented, I wondered if the type: might be wrong... indeed I had js.  Might be worth mentioning it as a reminder in the readme.  

Now to figure out how to get the google timer to display properly (apparently requires a template).

Thank you!
